---
title: "Dashboard_DwC_temporal"
author: "Ashwin Agrawal"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
suppressMessages(library(rgbif))
suppressMessages(library(sp))
suppressMessages(library(spatialEco))
suppressMessages(library(ggmap))
suppressMessages(library(plyr))
suppressMessages(library(htmlTable))
suppressMessages(library(bdvis))
suppressMessages(library(plotly))
suppressMessages(library(pracma))
suppressMessages(library(xtable))
suppressMessages(library(htmlTable))
d1 <- occ_data(
  country = "AU",     # Country code for australia
  classKey= 359,      # Class code for mammalia
  limit=50000,
  hasCoordinate = T
  
)

X<-d1$data



```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
 selectInput("clusterNum1", label = h3("Cluster number"), 
    choices = list( "1" = 1, "2" = 2, "3" = 3, "4" = 4,"5" = 5,"6"=6,"7"=7,"8"=8,"9"=9,"10"=10,"11"=11,"12"=12), 
    selected = 1)
```

Plotting the data based on month identified.
Sample data used is Australian Mammals.

```{r}
 selectInput("clusterNum", label = h3("Cluster number"), 
    choices = list( "2015" = 2015, "2016" = 2016, "2017" = 2017), 
    selected = 2016)
```

Plotting the data based on year identified.
Sample data used is Australian Mammals.

```{r}
#
selectedData <- reactive({
  
  #X<-subset(X,select=c(eventDate,month,year))
  num <- reactive(as.integer(input$clusterNum))
  data_year<-subset(X,X$year==num())
  data_year
   
})
```

```{r}
 
selectedData1<- reactive({
  
  #X<-subset(X,select=c(eventDate,month,year))
  num1 <- reactive(as.integer(input$clusterNum1))
  month_data<-subset(X,X$month==num1())
  month_data
    
})
```



Column {.tabset}
-----------------------------------------------------------------------

###Bar-plot
    
```{r}
library(ggplot2)
 
  renderPlot({
    c_2<-ddply(selectedData1(),~year,summarise,frequency=length((year)))
  ggplot(c_2, aes(x=year,y=frequency)) + geom_bar(stat="identity")
 
  
  })
  
```

###Choronorogram


```{r}
library(bdvis)
 
  renderPlot({
    data_bdvis<-selectedData1()
    names(data_bdvis)[names(data_bdvis) == "eventDate"] <- "Date_collected"
     chronohorogram(data_bdvis)
 
  
  })
  
```


Column {.tabset}
-----------------------------------------------------------------------

### Bar-plot


```{r}
library(ggplot2)

renderPlot({
  c_1<-ddply(selectedData(),~month,summarise,frequency=length((month)))
  ggplot(c_1, aes(x=month,y=frequency)) + geom_bar(stat="identity")
})
```

###Tempolar

```{r}
library(bdvis)

renderPlot({
   data_tempolar<-selectedData()
    names(data_tempolar)[names(data_tempolar) == "eventDate"] <- "Date_collected"
     tempolar(data_tempolar,timescale = "m")
  
})
```


